"""Summarizes results/*.json (agentsafe-mcp inspect --json) into RESULTS.md's tables. Standard library only."""
import glob
import json
import os
import re
import sys
from datetime import date

READ_VERB = re.compile(r"^(get|fetch|list|search|read|query|find|describe|retrieve|view|show|lookup|count)(_|-|[A-Z]|$)")


def maintainers():
    out = {}
    with open("servers.tsv") as f:
        for line in f:
            if line.strip() and not line.startswith("#"):
                ident, who, _ = line.rstrip("\n").split("\t", 2)
                out[ident] = who
    return out


def bare(name, ident):
    """The tool's verb, without a server prefix (hubspot-list-objects, razorpay's fetch_order)."""
    for p in (ident + "_", ident + "-", "hubspot-"):
        if name.startswith(p):
            return name[len(p):]
    return name


def main():
    who = maintainers()
    rows, total = [], dict(tools=0, writes=0, keyed=0, annotated=0, misread=0)
    for path in sorted(glob.glob("results/*.json")):
        ident = os.path.basename(path)[:-5]
        d = json.load(open(path))
        tools = d["tools"]
        writes = [t for t in tools if t["write"]]
        keyed = [t for t in writes if t.get("key_argument")]
        annotated = sum(t["annotated"] for t in tools)
        misread = [t for t in writes if READ_VERB.match(bare(t["name"], ident))]
        r = dict(id=ident, who=who.get(ident, "?"), server=d["server"], version=d["version"], tools=len(tools),
                 writes=len(writes), keyed=len(keyed), annotated=annotated, misread=len(misread))
        rows.append(r)
        for k in total:
            total[k] += r[k]
    w = sys.stdout.write
    w(f"# MCP server scan: results\n\nGenerated by `run.sh` on {date.today().isoformat()} from `results/`. "
      "See README.md for the method and its limits.\n\n")
    pct = lambda a, b: f"{100 * a / b:.0f}%" if b else "-"
    w(f"**{len(rows)} servers, {total['tools']} tools. {total['writes']} ({pct(total['writes'], total['tools'])}) "
      f"are not marked read-only. {total['keyed']} of them take an idempotency key.** "
      f"{total['annotated']} tools ({pct(total['annotated'], total['tools'])}) carry annotations; "
      f"{total['misread']} tools named like reads (get, fetch, list...) are not marked read-only.\n\n")
    w("| Server | Maintained by | Version | Tools | Not read-only | With a key argument | Annotated | Read-named, not read-only |\n")
    w("|---|---|---|--:|--:|--:|--:|--:|\n")
    for r in rows:
        w(f"| `{r['id']}` | {r['who']} | {r['version']} | {r['tools']} | {r['writes']} | {r['keyed']} | "
          f"{r['annotated']} | {r['misread']} |\n")
    w(f"| **total** | | | **{total['tools']}** | **{total['writes']}** | **{total['keyed']}** | "
      f"**{total['annotated']}** | **{total['misread']}** |\n")


if __name__ == "__main__":
    main()
